# Generated by Django 4.2.23 on 2025-07-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcedchoiceitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='likertitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Mandarin Chinese'), ('es', 'Spanish'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('pa', 'Punjabi'), ('de', 'German'), ('jv', 'Javanese'), ('wuu', 'Wu Chinese'), ('ms', 'Malay/Indonesian'), ('te', 'Telugu'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('fr', 'French'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('tr', 'Turkish'), ('it', 'Italian'), ('yue', 'Yue Chinese (Cantonese)'), ('th', 'Thai'), ('gu', 'Gujarati'), ('jcn', 'Jin Chinese'), ('fa', 'Persian'), ('pl', 'Polish'), ('ps', 'Pashto'), ('kn', 'Kannada'), ('hsn', 'Xiang Chinese'), ('ml', 'Malayalam'), ('su', 'Sundanese'), ('ha', 'Hausa'), ('or', 'Odia (Oriya)'), ('my', 'Burmese'), ('hak', 'Hakka'), ('uk', 'Ukrainian'), ('bho', 'Bhojpuri'), ('tl', 'Tagalog (Filipino)'), ('yo', 'Yoruba'), ('sd', 'Sindhi'), ('arz', 'Arabic (Egyptian Spoken)'), ('nl', 'Dutch'), ('apc', 'Sa’idi Arabic'), ('ku', 'Northern Kurdish'), ('ro', 'Romanian'), ('nl', 'Dutch'), ('el', 'Greek'), ('cs', 'Czech'), ('sv', 'Swedish'), ('hu', 'Hungarian'), ('be', 'Belarusian'), ('sr', 'Serbian'), ('az', 'Azerbaijani'), ('fi', 'Finnish'), ('sk', 'Slovak'), ('bg', 'Bulgarian'), ('no', 'Norwegian'), ('da', 'Danish'), ('he', 'Hebrew'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('hr', 'Croatian'), ('mn', 'Mongolian'), ('sl', 'Slovenian'), ('et', 'Estonian'), ('sq', 'Albanian'), ('mk', 'Macedonian'), ('lb', 'Luxembourgish'), ('ga', 'Irish'), ('cy', 'Welsh'), ('ca', 'Catalan'), ('eu', 'Basque'), ('gl', 'Galician'), ('af', 'Afrikaans')], max_length=20),
        ),
    ]
